# Generated by Django 5.2.9 on 2025-12-15 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ascenseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=255)),
                ('marque', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(max_length=255, unique=True)),
                ('charge', models.CharField(choices=[('450 Kg', '450 Kg'), ('630 Kg', '630 Kg'), ('800 Kg', '800 Kg'), ('1000 Kg', '1000 Kg'), ('1500 Kg', '1500 Kg'), ('2000 Kg', '2000 Kg')], max_length=15)),
                ('date_installation', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ascenseurs', to='gestion.client')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(default='Adresse inconnue', max_length=255)),
                ('date_intervention', models.DateField()),
                ('type_intervention', models.CharField(choices=[('maintenance', 'Maintenance'), ('reparation', 'Réparation'), ('installation', 'Installation'), ('autre', 'Autre')], max_length=20)),
                ('statut', models.CharField(choices=[('planifiée', 'Planifiée'), ('en cours', 'En cours'), ('terminée', 'Terminée')], default='planifiée', max_length=20)),
                ('fichier_pva', models.FileField(blank=True, null=True, upload_to='pva_files/')),
                ('note', models.TextField(blank=True, null=True)),
                ('ascenseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='gestion.ascenseur')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='gestion.client')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
