# Generated by Django 5.1.4 on 2024-12-25 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_ascenseur_client_alter_intervention_statut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervention',
            old_name='date',
            new_name='date_intervention',
        ),
        migrations.AddField(
            model_name='intervention',
            name='adresse',
            field=models.CharField(default='Adresse Inconnue', max_length=255),
        ),
        migrations.AddField(
            model_name='intervention',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='gestion.client'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='fichier_pva',
            field=models.FileField(blank=True, null=True, upload_to='pva_files/'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ascenseur',
            name='charge',
            field=models.CharField(choices=[('450 Kg', '450 Kg'), ('630 Kg', '630 Kg'), ('800 Kg', '800 Kg'), ('1000 Kg ', '1000 Kg'), ('1500 Kg', '1500 Kg'), ('2000 Kg', '2000 Kg')], max_length=15),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='ascenseur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='gestion.ascenseur'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='statut',
            field=models.CharField(choices=[('planifiée', 'Planifiée'), ('en cours', 'En cours'), ('terminée', 'Terminée')], default='planifiée', max_length=20),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='technicien',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='type_intervention',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('reparation', 'Réparation'), ('installation', 'Installation'), ('autre', 'Autre')], max_length=20),
        ),
    ]
