# Generated by Django 5.2.9 on 2026-03-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_client_code_postal_client_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervention',
            old_name='note',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='client',
        ),
        migrations.AddField(
            model_name='ascenseur',
            name='capacite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ascenseur',
            name='dernier_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ascenseur',
            name='emplacement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ascenseur',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ascenseur',
            name='nombre_etages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ascenseur',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ascenseur',
            name='prochain_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ascenseur',
            name='statut',
            field=models.CharField(choices=[('operationnel', 'Opérationnel'), ('maintenance', 'En maintenance'), ('hors_service', 'Hors service'), ('suspendu', 'Suspendu')], default='operationnel', max_length=20),
        ),
        migrations.AddField(
            model_name='intervention',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='priority',
            field=models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='statut',
            field=models.CharField(choices=[('scheduled', 'Planifiée'), ('in-progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='type_intervention',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('repair', 'Réparation'), ('inspection', 'Contrôle')], max_length=20),
        ),
    ]
