# Generated by Django 5.2.9 on 2025-12-04 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_rename_date_intervention_date_intervention_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascenseur',
            name='charge',
            field=models.CharField(choices=[('450 Kg', '450 Kg'), ('630 Kg', '630 Kg'), ('800 Kg', '800 Kg'), ('1000 Kg', '1000 Kg'), ('1500 Kg', '1500 Kg'), ('2000 Kg', '2000 Kg')], max_length=15),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='adresse',
            field=models.CharField(default='Adresse inconnue', max_length=255),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='ascenseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='gestion.ascenseur'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='gestion.client'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
