# Generated by Django 5.2.9 on 2026-03-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ascenseur',
            name='clientId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
