# Generated by Django 5.2.9 on 2026-03-31 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_ascenseur_clientid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ascenseur',
            old_name='date_installation',
            new_name='annee_installation',
        ),
    ]
