# Generated by Django 5.2.9 on 2026-03-31 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_rename_date_installation_ascenseur_annee_installation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ascenseur',
            name='clientId',
        ),
    ]
