# Generated by Django 5.2.9 on 2026-03-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_remove_ascenseur_clientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascenseur',
            name='modele',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ascenseur',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
