# Generated by Django 5.2.9 on 2026-03-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_ascenseur_modele_alter_ascenseur_numero_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascenseur',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
