# Generated by Django 5.2.9 on 2026-04-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_ascenseur_numero_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='priority',
            field=models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='statut',
            field=models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='type_intervention',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('reparation', 'Réparation'), ('controle', 'Contrôle')], max_length=20),
        ),
    ]
