# Generated by Django 5.2.9 on 2026-04-01 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_intervention_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='fichier_pva',
        ),
        migrations.AddField(
            model_name='intervention',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='gestion.client'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='priority',
            field=models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], default='moyenne', max_length=20),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='statut',
            field=models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20),
        ),
    ]
