# Generated by Django 5.2.9 on 2026-04-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_remove_intervention_fichier_pva_intervention_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
