# Generated by Django 5.2.9 on 2026-04-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_intervention_location_intervention_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ascenseur',
            old_name='annee_installation',
            new_name='date_installation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='code_postal',
        ),
    ]
