# Generated by Django 5.2.9 on 2026-06-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_client_adresse_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('technicien', 'Technicien'), ('manager', 'Manager'), ('readonly', 'Readonly')], max_length=50),
        ),
    ]
